version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_BASICAUTH_USERNAME=rootuser
      - ME_CONFIG_BASICAUTH_PASSWORD=rootpass
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
volumes:
  mongodb_data:

networks:
  default:
    name: mongodb_network